"""Generate configs/sweep_main/ from the SWEEP matrix below.

Each cell is a tiny override of `configs/_canonical.py`. Edit SWEEP and re-run
this script to regenerate the 10 cells. Hand-edits to the generated files are
overwritten.

Override grammar
----------------
Each row's `disc_overrides` and `solver_overrides` are dicts; any field
of `DiscretizationConfig` / `SolverConfig` is dialable. Examples:
    {"state_grid_sizes": (9, 9, 9)}
    {"state_n_stds": (2.5, 2.5, 2.5)}            # widen ergodic coverage
    {"n_state_quad_nodes": (3, 3, 5), "n_eps_nodes": 5}
Empty dict -> inherit canonical with no overrides.

To dial a value across ALL cells (e.g. widen `state_n_stds` everywhere),
edit `configs/_canonical.py` instead, then re-run this script.
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTDIR = PROJECT_ROOT / "configs" / "sweep_main"
OUTDIR.mkdir(parents=True, exist_ok=True)


def _cap(c: float) -> dict:
    """Symmetric alpha cap shorthand: 5.0 -> {alpha_min: -5, alpha_max: 5}."""
    return {"alpha_min": -c, "alpha_max": c}


# Each row: (idx, label, disc_overrides, solver_overrides, est_hr).
# An empty dict means "inherit canonical for that block."
# `est_hr` is purely informational (used by the launcher heuristic).
#
# v2 collapsed matrix: all cells inherit canonical alpha cap (±6) — no per-cell
# alpha override. Each cell isolates ONE knob from the canonical baseline so
# each bundle answers a single sensitivity question. Indexed in ascending
# c6i.24xlarge cost so the alternated 2-line allocation gives cheap-first
# bundle drops.
SWEEP = [
    (1, "base",       {},                                            {}, 1),
    (2, "state33",    {"n_state_quad_nodes": (3, 3, 5)},             {}, 1),
    (3, "grid9_base", {"state_grid_sizes": (9, 9, 9)},               {}, 1),
    (4, "inc55",      {"n_eps_nodes": 5, "n_eta_nodes": 5},          {}, 2),
    (5, "state44",    {"n_state_quad_nodes": (4, 4, 5)},             {}, 4),
]


TEMPLATE = '''"""Sweep config: {label}

Generated by scripts/_gen_sweep_main.py from configs/_canonical.py.
Edit the SWEEP matrix in the generator (not this file) to change the cell.

Overrides applied:
  disc:   {disc_summary}
  solver: {solver_summary}
  est. compute hours: ~{est_hr}
"""

from configs._canonical import (
    PREDICTABILITY_SYSTEM,
    BASE_CONFIG,
    CANONICAL_DISC,
    CANONICAL_SOLVER,
)

BUNDLE_SUFFIX = "_{label}"

base_config = BASE_CONFIG
disc_config_template = {disc_expr}
solver_config = {solver_expr}
'''


def _render_replace(name: str, overrides: dict) -> str:
    """Render either `NAME` or `NAME._replace(field=value, ...)`."""
    if not overrides:
        return name
    args = ", ".join(f"{k}={v!r}" for k, v in overrides.items())
    return f"{name}._replace({args})"


def _summarize(overrides: dict) -> str:
    if not overrides:
        return "(canonical, no overrides)"
    return ", ".join(f"{k}={v!r}" for k, v in overrides.items())


def main() -> None:
    labels = [row[1] for row in SWEEP]
    if len(set(labels)) != len(labels):
        dupes = [s for s in labels if labels.count(s) > 1]
        raise SystemExit(f"duplicate labels (would overwrite each other in S3): {set(dupes)}")

    for idx, label, disc_overrides, solver_overrides, est_hr in SWEEP:
        body = TEMPLATE.format(
            label=label,
            disc_summary=_summarize(disc_overrides),
            solver_summary=_summarize(solver_overrides),
            disc_expr=_render_replace("CANONICAL_DISC", disc_overrides),
            solver_expr=_render_replace("CANONICAL_SOLVER", solver_overrides),
            est_hr=est_hr,
        )
        fname = f"{idx:02d}_{label}.py"
        (OUTDIR / fname).write_text(body)
        print(f"wrote configs/sweep_main/{fname}  (~{est_hr}h)")

    total_hr = sum(row[4] for row in SWEEP)
    max_hr = max(row[4] for row in SWEEP)
    print(f"\n{len(SWEEP)} configs total. Sequential compute: ~{total_hr}h")
    print(f"Wall clock if all run in parallel: ~{max_hr}h (longest config)")
    print()
    print("Launch with:")
    print("  python scripts/launch_sweep.py configs/sweep_main/ \\")
    print("      --instance-type c6i.4xlarge --key-name hugo-thesis")


if __name__ == "__main__":
    main()
