"""Sweep config: base

Generated by scripts/_gen_sweep_main.py from configs/_canonical.py.
Edit the SWEEP matrix in the generator (not this file) to change the cell.

Overrides applied:
  disc:   (canonical, no overrides)
  solver: (canonical, no overrides)
  est. compute hours: ~1
"""

from configs._canonical import (
    PREDICTABILITY_SYSTEM,
    BASE_CONFIG,
    CANONICAL_DISC,
    CANONICAL_SOLVER,
)

BUNDLE_SUFFIX = "_base"

base_config = BASE_CONFIG
disc_config_template = CANONICAL_DISC
solver_config = CANONICAL_SOLVER
