"""Sweep config: state33

Generated by scripts/_gen_sweep_main.py from configs/_canonical.py.
Edit the SWEEP matrix in the generator (not this file) to change the cell.

Overrides applied:
  disc:   n_state_quad_nodes=(3, 3, 5)
  solver: (canonical, no overrides)
  est. compute hours: ~1
"""

from configs._canonical import (
    PREDICTABILITY_SYSTEM,
    BASE_CONFIG,
    CANONICAL_DISC,
    CANONICAL_SOLVER,
)

BUNDLE_SUFFIX = "_state33"

base_config = BASE_CONFIG
disc_config_template = CANONICAL_DISC._replace(n_state_quad_nodes=(3, 3, 5))
solver_config = CANONICAL_SOLVER
