"""Sweep config: grid9_base

Generated by scripts/_gen_sweep_main.py from configs/_canonical.py.
Edit the SWEEP matrix in the generator (not this file) to change the cell.

Overrides applied:
  disc:   state_grid_sizes=(9, 9, 9)
  solver: (canonical, no overrides)
  est. compute hours: ~1
"""

from configs._canonical import (
    PREDICTABILITY_SYSTEM,
    BASE_CONFIG,
    CANONICAL_DISC,
    CANONICAL_SOLVER,
)

BUNDLE_SUFFIX = "_grid9_base"

base_config = BASE_CONFIG
disc_config_template = CANONICAL_DISC._replace(state_grid_sizes=(9, 9, 9))
solver_config = CANONICAL_SOLVER
