"""Sweep config: inc55

Generated by scripts/_gen_sweep_main.py from configs/_canonical.py.
Edit the SWEEP matrix in the generator (not this file) to change the cell.

Overrides applied:
  disc:   n_eps_nodes=5, n_eta_nodes=5
  solver: (canonical, no overrides)
  est. compute hours: ~2
"""

from configs._canonical import (
    PREDICTABILITY_SYSTEM,
    BASE_CONFIG,
    CANONICAL_DISC,
    CANONICAL_SOLVER,
)

BUNDLE_SUFFIX = "_inc55"

base_config = BASE_CONFIG
disc_config_template = CANONICAL_DISC._replace(n_eps_nodes=5, n_eta_nodes=5)
solver_config = CANONICAL_SOLVER
